# -*- coding: utf-8 -*-
"""LabWaste

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KE-OGMtw1tdHO0Qq030hrnI62IBOGEDY
"""

pip install rdkit

pip install py3Dmol

import py3Dmol
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem

# โหลดฐานข้อมูลสารเคมีจากไฟล์ CSV
file_path = "lab_chemicals_database_2.csv"
df = pd.read_csv(file_path)

def get_chemical_info(smiles):
    "ดึงข้อมูลสารเคมีจากฐานข้อมูล CSV"
    chem_info = df[df["SMILES"] == smiles]
    if not chem_info.empty:
        return chem_info.iloc[0].to_dict()
    return None

def show_3D_molecule(smiles):
    "แสดงโครงสร้างโมเลกุลสามมิติ"
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        mol_h = Chem.AddHs(mol)
        AllChem.EmbedMolecule(mol_h, AllChem.ETKDG())
        mol_block = Chem.MolToMolBlock(mol_h)
        viewer = py3Dmol.view(width=400, height=400)
        viewer.addModel(mol_block, "mol")
        viewer.setStyle({"stick": {}, "sphere": {"radius": 0.3}})
        viewer.zoomTo()
        viewer.show()
    else:
        print("❌ ไม่สามารถแสดงโครงสร้าง 3D ได้")

def check_disposal(smiles):
    "ตรวจสอบว่าสารควรทิ้งลงอ่างหรือไม่"
    info = get_chemical_info(smiles)
    if not info:
        print("⚠️ ไม่มีข้อมูลของสารนี้ในฐานข้อมูล!")
        return

    name = info["Name"]
    solubility = info["WaterSolubility"]
    pKa = info["pKa"]
    waste_category = info["WasteCategory"]
    disposal_method = info["DisposalMethod"]

    print(f"🔬 ชื่อสาร: {name}")
    print(f"💧 การละลายน้ำ: {solubility} g/L")
    print(f"⚖️ ค่า pKa: {pKa}")
    print(f"🗑️ ประเภทของเสีย: {waste_category}")
    print(f"⚠️ วิธีการกำจัด: {disposal_method}")

    if disposal_method.startswith("Non-hazardous chemicals") or disposal_method.startswith("Can be disposed of in the drain"):
        print("✅ สามารถกำจัดสารนี้ได้ตามขั้นตอนที่เหมาะสม")
    else:
        print("🛑 ห้ามทิ้งสารนี้ลงอ่างล้างอุปกรณ์!")
        print("💡 โปรดปฏิบัติตามแนวทางการกำจัดของเสียอันตรายอย่างถูกต้อง")

# รับข้อมูลจากผู้ใช้
while True:
    smiles_input = input("\n🔬 กรอกสูตรเคมี SMILES (หรือ 'exit' เพื่อออก): ").strip()
    if smiles_input.lower() == "exit":
        print("👋 ขอบคุณที่ใช้โปรแกรม!")
        break
    elif smiles_input:
        check_disposal(smiles_input)
        show_3D_molecule(smiles_input)
    else:
        print("⚠️ กรุณากรอกสูตรเคมีที่ถูกต้อง")